### ISSUE TITLE
Color recording

### ISSUE THREAD

**Issue by dermanu** [neurojak/pySpinCapture#2]
Hi there,

is there a possibility to record and save RGB video using skvideo? 

All the best

**Comment by neurojak** [comment]
Yep, color video should be possible using FFMPEG (skvideo is just the python wrapper around this) & H.264 encoding, but you will need to change the camera parameters for a color camera. I don't have one to test, but let me know if you run into any problems.

**Comment by dermanu** [comment]
I used so far cv2 for writing the frames in "real-time" from the FLIR cameras. However, that was not fast enough for my use-case, even when multithreaded. I tried your approach, but so far no luck. Just found out NVEnc only supports YUV444. Will try around a bit more and let you know.

**Comment by neurojak** [comment]
I recently got a Blackfly S color camera and 'm looking into this more now. It looks like some NVIDIA GPUs support more YUV formats for NVEnc: https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new.

**Comment by dermanu** [comment]
Yes, I got it running using the h264_nvenc codec. It allows for super-fast encoding. However, most Nvidia graphic cards only support two encoding sessions at a time. You can use a patch to allow for more (https://github.com/keylase/nvidia-patch). 

As PixelFormat I used RGB8Packed. It was a lot of trying around to get it to work.

**Comment by neurojak** [comment]
Great, thanks. I also got it running with RGB8Packed / RGB24. I'll close the issue and post the color version of the code for anyone else who is interested.
