### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by BerezhnoyD** [neurojak/pySpinCapture#4]
Hi there.
I'm trying to record a video with a single setup - one Blackfly S camera 200hz fps + CameraCapture.py script,
but from time to time it just throws the PC into a blackscreen running out of RAM, usually after 10 mins of recording.
I heard there could be a problem with the native Spinnaker API (I use 2.6). Have anyone experienced this issue? And what
are the ways to debug the problem?

Thank you in advance.
Sincerely,
Daniil

**Comment by neurojak** [comment]
Hi Daniil,

I have not seen that particular response (my computer will just drop frames and throw an error at end), but you can drive up RAM usage fairly quickly if pushing the limits on frame rate. You can open Task Manager on Windows (not sure of equivalent on other OS) and see the RAM usage go up while recording if FFMPEG cannot keep up with the incoming frames on your machine, in which case I don't know what you can do other than decrease the frame rate.  I have a fast computer FWIW and I steam 3 cameras at 512x512px at 400Hz regularly with no issues, if using the GPU encoding; without GPU (native FFMPEG, not hardware accelerated) I think my max frame rate was around 200fps.

Hope that's helpful,
-Jason
